name: Publish Superverse Pre-Releases to PyPI and TestPyPI
on:
  push:
    tags:
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+a[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+b[0-9]"
      - "[0-9]+.[0-9]+[0-9]+.[0-9]+rc[0-9]"

  workflow_dispatch:

jobs:
  build-and-publish-pre-release-pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🏗️ Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*

      - name: 🚀 Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.12

      - name: 🚀 Publish to Test-PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          repository-url: https://test.pypi.org/legacy/
